# Generated by Django 3.0 on 2020-06-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='stripe_customer_id',
            field=models.CharField(max_length=150),
        ),
    ]
